hydra:
  output_subdir: null  
  run:
    dir: .

defaults:
  - process: process1
  - model: model1
  - _self_

data:
  model_plots: docs/

  raw: data/raw/sample.csv
  processed: data/processed/processed.csv
  final: data/final/final.csv
  train_percentage: 0.8
  model_geo_batch: 500
  final_images: data/final/images
  obj: /home/oriol/tools/3d_vae/data/obj/to_train
  original_obj: data/obj/original_obj.obj
  created_obj: data/obj/created_obj.obj

